name: "Build and release docker image: architect-solana"
on:
  workflow_dispatch:
jobs:
  Build-and-push-Docker-image:
    name: "Build and push Docker image"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push Docker image (slurp)"
        run: |
          depot build --push --project 2m5pzqgvpk --build-platform "linux/arm64" \
            -t afintech/architect-solana:latest .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}